import os

# examples of Snakemake workflows:
# https://snakemake.github.io/snakemake-workflow-catalog/


# include rules here
include: "rules/pack.smk"
include: "rules/neurosuite.smk"

src_path = config['src_path']
dst_path = config['dst_path']
session  = config['sessions'][0]

def build_file_path(where, session, file_name):
    return os.path.join(where, session.split('_')[0], session, file_name)


# rule for 
# - complete spike sorting with neurosuite / klustakwik
# - pack main metadata into HDF5
rule all:
    input:
        build_file_path(dst_path, session, '%s.fil' % session),
        build_file_path(dst_path, session, 'meta.h5')