# run snakemake from ../workflow folder:
# snakemake -n --configfile=../config/andrey/016672.yaml --use-conda --cores=20
# 
# find files / modified date
# find . -name phy.log -printf "%p %TY-%Tm-%Td %TH:%TM:%TS %Tz\n"
# 
# mount nevermind via SSHFS
# sshfs sobolev@10.153.172.1:/nevermind.neuro/share/ag-grothe nevermind
# sshfs andrey@10.153.170.1:/storage2 storage2
# unmount
# sudo diskutil umount force /Users/andrey/nevermind

blocks:  # blocks of pipeline to run
  meta: True         # pack main metadata into HDF5
  performance: True   # performance metrics
  DLC: True        # Deep lab cut
  MoSeq: True        # MoSeq
  descendants: True   # speed, HD etc. from MoSeq and others
  Audio: False       # process audio data
  LFP: False          # extract LFP
  neurosuite: False  # sorting with neurosuite / klustakwik
  kilosort: True  # sorting with kilosort
  units: True      # extract spike trains from sorted data
  AEPs: False         # extract Auditory Evoked Responses
  PSTH_bar: True
  PSTH_bootstrap: False
  PSTH_shuffle: False
  PSTH_bnMAPs: False
  spatial: False
  population: False
  coherence: False
  manifold_states: False
  metronome: False
  video: False
  sound_phase_lock: True
  segments: True
  activity_matrices: True
  ensembles: False
  covariance: False
  vectors: True
  state_decoder_unit_mx: True

session_IDs:  
  # controls
  # - "016672_devSITnostim_2025-10-15_17-01-06"
  # - "016672_devSITnostim_2025-10-16_10-47-04"
  # - "016672_devSITnostim_2025-10-16_11-05-08"
  # - "016672_devSITpassive_2025-10-17_10-41-44"
  # - "016672_devSITpassive_2025-10-17_10-58-03"
  # - "016672_devSITnostim_2025-10-20_14-50-47"
  # - "016672_devSITpassive_2025-10-20_15-51-04"
  # - "016672_devSITnostim_2025-10-20_16-04-14"  # ThalD session
  # - "016672_devSITpassive_2025-10-21_21-10-10"
  # - "016672_devSITnostim_2025-10-21_22-02-56"
  # - "016672_devSITnostim_2025-10-23_14-46-06"
  # - "016672_devSITnostim_2025-10-24_16-59-14"
  # - "016672_devSITpassive_2025-10-27_12-19-32"
  # - "016672_devSITnostim_2025-10-27_13-18-35"
  # - "016672_devSITnostim_2025-10-28_20-47-37"
  # - "016672_devSITpassive_2025-10-28_21-38-11"
  # - "016672_devSITpassive_2025-10-29_13-17-35"
  # - "016672_devSITnostim_2025-10-29_14-23-34"
  # - "016672_devSITnostim_2025-10-30_11-07-44"
  # - "016672_devSITpassive_2025-10-30_13-28-46"
  # - "016672_devSITpassive_2025-10-31_14-37-30"
  # - "016672_devSITnostim_2025-11-03_10-25-42"
  # - "016672_devSITpassive_2025-11-03_13-32-57"
  # - "016672_devSITpassive_2025-11-04_09-57-02"
  # - "016672_devSITnostim_2025-11-04_10-56-55"
  # - "016672_devSITnostim_2025-11-05_10-29-43"
  # - "016672_devSITpassive_2025-11-05_11-35-46"

  # active sessions
  - "016672_devSITactive_2025-10-20_15-13-28"  # naive
  - "016672_devSITactive_2025-10-21_21-25-15"  # learning
  - "016672_devSITactive_2025-10-23_15-05-37"  # learning
  - "016672_devSITactive_2025-10-24_17-18-47"
  - "016672_devSITactive_2025-10-27_12-36-37"
  - "016672_devSITactive_2025-10-28_21-02-10"
  - "016672_devSITactive_2025-10-29_13-36-00"
  - "016672_devSITactive_2025-10-30_11-23-50"
  # - "016672_devSITactive_2025-10-31_14-50-34"  # good restored session (26 mins)
  - "016672_devSITactive_2025-10-31_15-23-44"
  - "016672_devSITactive_2025-11-03_10-39-56"
  - "016672_devSITactive_2025-11-04_10-11-10"
  - "016672_devSITactive_2025-11-05_10-45-16"  # last session with box controls
  - "016672_devSITactive_2025-11-06_21-16-33"
  - "016672_devSITactive_2025-11-07_13-18-09"
  - "016672_devSITactive_2025-11-10_16-03-29"
  - "016672_devSITactive_2025-11-11_17-41-18"  # R - channels flipped, but should be still fine
  - "016672_devSITactive_2025-11-12_14-58-44"  # R
  - "016672_devSITactive_2025-11-13_20-25-42"  # R - BGR 1195
  - "016672_devSITactive_2025-11-14_13-57-22"  # R - BGR 660
  - "016672_devSITactive_2025-11-17_13-56-04"  # L - distractors
  - "016672_devSITactive_2025-11-18_14-22-05"  # R - distractors
  - "016672_devSITactive_2025-11-19_14-42-36"  # L - distractors (so much noise..)
  

# source of raw data
#src_path: "/home/sobolev/nevermind_ag-grothe/Andrey/data/"
src_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw"

# destination for processed data
#dst_path: "/home/sobolev/nevermind_ag-grothe/Andrey/sandbox/4Kate/processed"
dst_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/processed/"

pack:
  drift_coeff: 0.000016666

# neurosuite / klustakwik config files
template_xml: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/016672/neurosuite.xml"
template_manual_json: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/016672/manual.json"
ndm_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/apps/ndm/usr/bin/"
kkwik_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/apps/kkwik/"
kwik_args: "-PenaltyMix 1.0 -MinClusters 85 -MaxClusters 85 -MaxPossibleClusters 500 -UseFeatures"

kilosort:
  settings_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/016672/kilosort.json"
  probe_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/016672/probe.json"
  save_preprocessed: False
  cuda_device: 1

# single units config: which sorter to use
units:
  source: 'kilosort'

# deep lab cut config files
#dlc_config_path: "/home/sobolev/nevermind_ag-grothe/Miguel/DeepLabCut/TrainedModels/implantedSIT-Miguel-2023-06-23/config.yaml"
dlc_config_path: "/home/sobolev/nevermind_ag-grothe/Miguel/DeepLabCut/TrainedModels/implantedSIT_newSetup-Miguel-2025-01-24/config.yaml"
dlc_shuffle: 1
dlc_trainingsetindex: 1

# moseq config files
moseq_model_path: '/mnt/nevermind.data-share/ag-grothe/Miguel/MoSeq/TrainedModels/hippoSIT2023_noTail_unfiltered/2023_07_13-15_08_10'
cuda_device_to_use: 3

# LFP configuration
lfp:
  n_channels: 384
  source_rate: 30000 # original LFP sampling rate in Hz
  target_rate: 1000  # target LFP sampling rate in Hz
  chunk_size_sec: 10  # chunk size for conversion in seconds
  aep_dur: 0.25  # Auditory evoked response duration in sec

# analysis configurations
psth:
  micro:
    latency: 0.25
    bin_count: 51
    shuf_iter_count: 100
    figsize: 4
  macro:
    latency: 7.25
    bin_count: 31
  bootstrap:
    latency: 0.25
    bin_count: 51
    boot_iter_count: 100

# neural manifolds
nMAP_electrodes:
    '009265': [1, 2]
    '009266': [1, 2]
    '57': [1]
    '60': [1, 2]

nMAP_segmentation:
  ft: 'tSNE'
  fp: 70
  speed_thresh: 0.04  # m/s
  margin: 5
  sigma: 0.1
  bin_count: 100
  shuffle_iter_count: 100

# behavioral manifolds
bMAP_segmentation:
  ft: 'tSNE'
  fp: 70
  speed_thresh: 0.04  # m/s
  margin: 5
  sigma: 0.12
  bin_count: 100
  shuffle_iter_count: 100

# metronome
metronome:
  split_ratio: 0.5

# Evoked / sustained manifold
nMAP_EV_SU:
  bin_size: 0.01
  ev_su_lag: 0.12
  k_width: 200  # sampled as activity matrix bins (10ms)
  smooth_su_size: 4  #  rectangular kernel size to smooth sustained part
  smooth_ev_size: 20  #  gaussian kernel size to smooth evoked part

# unit matrix + video merging
video:
  duration: 300  # in seconds
  overlap: 100  # in seconds
  crop_width: 900
  crop_height: 768
  scale_height: 1242
  overwrite: False

# PCA and pairwise correlations for sustained activity
coherence:
  comp_count: 10
  bin_size: 0.01
  win_sizes: [5, 10, 20, 30, 50, 75, 100, 150, 200, 300, 500, 750, 1000, 1500, 2000]  # in number of bins of bin_size
  sustained_start: 0.12

PSTH_micro_bnMAPs:
  units: []  # leave empty for all units

sound_phase_lock:
  n_shuffles: 100
  ipi_for_shuffle: 0.25

sound_phase_lock:
  n_shuffles: 100
  ipi_for_shuffle: 0.25

segments:
  ensembles: False
  tgt_sta_min_pulses: 13
  bgr_sta_min_pulses: 12
  sil_sta_min_pulses: 12
  bgr_run_min_pulses: 2
  sil_run_min_pulses: 4
  dis_sta_min_pulses: 4
  visits:
    min_pulses: 8
    radius: 0.05


vectors:
  min_mfr: 0.005
  unit_mx:
    group: 'mx_50ms'
    type: 'mx_sm20_z'
    step: 5
  units_to_exclude:
    '014393_ppcSIT_2025-04-23_20-27-09': ['2-300', '3-350']


ensembles:
    '014393_ppcSIT_2025-04-23_20-27-09': 
      'AL': ['2-300', '3-350']
    '014393_ppcSIT_2025-04-24_20-53-08': 
      'AL': ['2-324', '3-281', '4-282']
    '014393_ppcSIT_2025-04-25_15-42-45': 
      'AL': ['1-349', '3-280', '4-284']
    '014393_ppcSIT_2025-04-29_22-10-49': 
      'AL': ['1-164', '3-371']