blocks:  # blocks of pipeline to run
  meta: True         # pack main metadata into HDF5
  DLC: True         # Deep lab cut
  MoSeq: False        # MoSeq
  Audio: False       # process audio data
  LFP: True          # extract LFP
  units: True      # complete spike sorting with neurosuite / klustakwik
  AEPs: True         # extract Auditory Evoked Responses
  PSTH: True
  spatial: True
  shuffle: False
src_path: "/home/sobolev/nevermind_ag-grothe/Andrey/data/"
#src_path: "/home/sobolev/nevermind_ag-grothe/AG_Pecka/data/raw"
dst_path: "/home/sobolev/nevermind_ag-grothe/AG_Pecka/data/processed/"
dlc_config_path: "/home/sobolev/nevermind_ag-grothe/Miguel/DeepLabCut/TrainedModels/implantedSIT-Miguel-2023-06-23/config.yaml"
dlc_shuffle: 3
dlc_trainingsetindex: 0
cuda_device_to_use: 3
ndm_path: "/home/sobolev/nevermind_ag-grothe/AG_Pecka/apps/ndm/usr/bin/"
#ndm_path: "/home/sobolev/ndm/usr/bin/"
kkwik_path: "/home/sobolev/apps/kkwik/"
kwik_args: "-PenaltyMix 1.0 -MinClusters 85 -MaxClusters 85 -MaxPossibleClusters 200 -UseFeatures"
lfp:
  s_rate: 1000  # sampling rate in Hz
  aep_dur: 0.25  # Auditory evoked response duration in sec
psth:
  micro:
    latency: 0.25
    bin_count: 41
  macro:
    latency: 7.25
    bin_count: 41
session_IDs:  
  - "009265_hippoSIT_2023-02-24_09-53-26"
  - "009265_hippoSIT_2023-02-24_17-22-46"
  - "009265_hippoSIT_2023-02-27_10-18-32"
  - "009265_hippoSIT_2023-02-27_15-33-46"
  - "009265_hippoSIT_2023-02-28_09-16-50"
  - "009265_hippoSIT_2023-02-28_13-16-10"
  - "009265_hippoSIT_2023-02-28_20-45-04"
  - "009265_hippoSIT_2023-03-01_10-46-12"
  - "009265_hippoSIT_2023-03-02_09-32-54"
  - "009265_hippoSIT_2023-03-02_16-27-42"
  - "009265_hippoSIT_2023-03-02_20-11-35"
  - "009265_hippoSIT_2023-03-03_09-37-07"
  - "009265_hippoSIT_2023-03-03_16-00-47"
  - "009265_hippoSIT_2023-03-04_11-12-04"
  - "009265_hippoSIT_2023-03-05_11-52-17"
  - "009265_hippoSIT_2023-03-05_18-31-32"
  - "009265_hippoSIT_2023-03-08_18-10-07"
  - "009265_hippoSIT_2023-03-09_20-03-08"
  - "009265_hippoSIT_2023-03-10_09-57-34"
  - "009265_hippoSIT_2023-04-13_09-54-39"
  - "009265_hippoSIT_2023-04-20_11-39-02"