# run snakemake from ../workflow folder:
# snakemake -n --configfile=../config/andrey_gpuxxl_013608.yaml --use-conda --cores=20
#
# mount nevermind via SSHFS
# sshfs sobolev@10.153.172.1:/nevermind.neuro/share/ag-grothe nevermind
# sshfs andrey@10.153.170.1:/storage2 storage2
# unmount
# sudo diskutil umount force /Users/andrey/nevermind

blocks:  # blocks of pipeline to run
  meta: True         # pack main metadata into HDF5
  DLC: False        # Deep lab cut
  MoSeq: False        # MoSeq
  descendants: False   # speed, HD etc. from MoSeq and others
  Audio: False       # process audio data
  LFP: False          # extract LFP
  neurosuite: False  # sorting with neurosuite / klustakwik
  kilosort: True  # sorting with kilosort
  units: True      # extract spike trains from sorted data
  AEPs: False         # extract Auditory Evoked Responses
  PSTH_bar: True
  PSTH_bootstrap: False
  PSTH_shuffle: False
  PSTH_bnMAPs: False
  spatial: False
  population: False
  coherence: False
  manifold_states: False
  metronome: False
  video: False

session_IDs:  
  # - "013608_ppcSIT_2025-01-06_13-20-52"
  # - "013608_ppcSIT_2025-01-07_08-47-27"
  # - "013608_ppcSIT_2025-01-07_15-38-23"
  # - "013608_ppcSIT_2025-01-09_09-09-55"
  # - "013608_ppcSIT_2025-01-10_09-25-04"
  # - "013608_ppcSIT_2025-01-13_14-01-40"
  # - "013608_ppcSIT_2025-01-14_10-20-14"
  # - "013608_ppcSIT_2025-01-15_14-56-18"
  # - "013608_ppcSIT_2025-01-16_09-49-21"
  # - "013608_ppcSIT_2025-01-17_10-07-00"
  # - "013608_ppcSIT_2025-01-20_09-38-20"
  # - "013608_ppcSIT_2025-01-21_08-50-02"
  # - "013608_ppcSIT_2025-01-22_12-59-00"
  # - "013608_ppcSIT_2025-01-23_08-46-51"
  # - "013608_ppcSIT_2025-01-24_08-19-45"
  # - "013608_ppcSIT_2025-01-27_09-00-20"
  # - "013608_ppcSIT_2025-01-29_12-34-08"
  # - "013608_ppcSIT_2025-02-18_14-15-52"
  # - "013608_ppcSIT_2025-02-19_13-50-59"
  # - "013608_ppcSIT_2025-02-27_08-56-52"
  - "013608_ppcSIT_2025-02-28_16-23-29"
  - "013608_ppcSIT_2025-03-03_08-55-30"
  - "013608_ppcSIT_2025-03-04_09-17-16"
  - "013608_ppcSIT_2025-03-05_10-33-41"

# source of raw data
#src_path: "/home/sobolev/nevermind_ag-grothe/Andrey/data/"
src_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw"

# destination for processed data
#dst_path: "/home/sobolev/nevermind_ag-grothe/Andrey/sandbox/4Kate/processed"
dst_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/processed/"

pack:
  drift_coeff: 0.000016666

# neurosuite / klustakwik config files
template_xml: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/013608/neurosuite.xml"
template_manual_json: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/013608/manual.json"
ndm_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/apps/ndm/usr/bin/"
kkwik_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/apps/kkwik/"
kwik_args: "-PenaltyMix 1.0 -MinClusters 85 -MaxClusters 85 -MaxPossibleClusters 500 -UseFeatures"

kilosort:
  settings_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/013608/kilosort.json"
  probe_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/013608/probe.json"
  save_preprocessed: False
  cuda_device: 3

# single units config: which sorter to use
units:
  source: 'kilosort'

# deep lab cut config files
#dlc_config_path: "/home/sobolev/nevermind_ag-grothe/Miguel/DeepLabCut/TrainedModels/implantedSIT-Miguel-2023-06-23/config.yaml"
dlc_config_path: "/home/sobolev/nevermind_ag-grothe/Miguel/DeepLabCut/TrainedModels/implantedSIT_newSetup-Miguel-2025-01-24/config.yaml"
dlc_shuffle: 1
dlc_trainingsetindex: 1

# moseq config files
moseq_model_path: '/mnt/nevermind.data-share/ag-grothe/Miguel/MoSeq/TrainedModels/hippoSIT2023_noTail_unfiltered/2023_07_13-15_08_10'
cuda_device_to_use: 3

# LFP configuration
lfp:
  s_rate: 1000  # sampling rate in Hz
  aep_dur: 0.25  # Auditory evoked response duration in sec

# analysis configurations
psth:
  micro:
    latency: 0.25
    bin_count: 51
    shuf_iter_count: 100
    figsize: 4
  macro:
    latency: 7.25
    bin_count: 31
  bootstrap:
    latency: 0.25
    bin_count: 51
    boot_iter_count: 100

# neural manifolds
nMAP_electrodes:
    '009265': [1, 2]
    '009266': [1, 2]
    '57': [1]
    '60': [1, 2]

nMAP_segmentation:
  ft: 'tSNE'
  fp: 70
  speed_thresh: 0.04  # m/s
  margin: 5
  sigma: 0.1
  bin_count: 100
  shuffle_iter_count: 100

# behavioral manifolds
bMAP_segmentation:
  ft: 'tSNE'
  fp: 70
  speed_thresh: 0.04  # m/s
  margin: 5
  sigma: 0.12
  bin_count: 100
  shuffle_iter_count: 100

# metronome
metronome:
  split_ratio: 0.5

# Evoked / sustained manifold
nMAP_EV_SU:
  bin_size: 0.01
  ev_su_lag: 0.12
  k_width: 200  # sampled as activity matrix bins (10ms)
  smooth_su_size: 4  #  rectangular kernel size to smooth sustained part
  smooth_ev_size: 20  #  gaussian kernel size to smooth evoked part

# unit matrix + video merging
video:
  duration: 300  # in seconds
  overlap: 100  # in seconds
  crop_width: 900
  crop_height: 768
  scale_height: 1242
  overwrite: False

# PCA and pairwise correlations for sustained activity
coherence:
  comp_count: 10
  bin_size: 0.01
  win_sizes: [5, 10, 20, 30, 50, 75, 100, 150, 200, 300, 500, 750, 1000, 1500, 2000]  # in number of bins of bin_size
  sustained_start: 0.12

PSTH_micro_bnMAPs:
  units: []  # leave empty for all units