src_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/"
dst_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/processed/"
session_IDs: 
  - "60_SIT_2023-08-21_17-55-38"
dlc_config_path: "/mnt/nevermind.data-share/ag-grothe/Miguel/DeepLabCut/TrainedModels/implantedSIT-Miguel-2023-06-23/config.yaml"
dlc_shuffle: 3
dlc_trainingsetindex: 0
cuda_device_to_use: 3
blocks:  # blocks of pipeline to run
  meta: True         # pack main metadata into HDF5
  DLC: False         # Deep lab cut
  MoSeq: False        # MoSeq
  Audio: False       # process audio data
  LFP: False          # extract LFP
  SS_SI: False       # run sikesorting with spike interface
  SS_kwik: True      # complete spike sorting with neurosuite / klustakwik
ndm_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/apps/ndm/usr/bin/"
kkwik_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/apps/kkwik/"
kwik_args: "-PenaltyMix 1.0 -MinClusters 85 -MaxClusters 85 -MaxPossibleClusters 200 -UseFeatures"
lfp:
  s_rate: 1000  # sampling rate in Hz
  aep_dur: 0.25  # Auditory evoked response duration in sec
psth:
  micro:
    latency: 0.25
    bin_count: 41
  macro:
    latency: 7.25
    bin_count: 41