# run snakemake from ../workflow folder:
# snakemake -n --configfile=../config/andrey/017276.yaml --use-conda --cores=20
# 
# find files / modified date
# find . -name phy.log -printf "%p %TY-%Tm-%Td %TH:%TM:%TS %Tz\n"
# 
# mount nevermind via SSHFS
# sshfs sobolev@10.153.172.1:/nevermind.neuro/share/ag-grothe nevermind
# sshfs andrey@10.153.170.1:/storage2 storage2
# unmount
# sudo diskutil umount force /Users/andrey/nevermind

blocks:  # blocks of pipeline to run
  meta: False         # pack main metadata into HDF5
  performance: False   # performance metrics
  DLC: False        # Deep lab cut
  MoSeq: False        # MoSeq
  descendants: False   # speed, HD etc. from MoSeq and others
  Audio: False       # process audio data
  LFP: False          # extract LFP
  neurosuite: False  # sorting with neurosuite / klustakwik
  kilosort: False  # sorting with kilosort
  units: False      # extract spike trains from sorted data
  AEPs: False         # extract Auditory Evoked Responses
  PSTH_bar: False
  PSTH_bootstrap: False
  PSTH_shuffle: False
  STRF_passive: False
  PSTH_bnMAPs: False
  spatial: False
  population: False
  coherence: False
  manifold_states: False
  metronome: False
  video: False
  sound_phase_lock: False
  segments: True
  activity_matrices: True
  ensembles: False
  covariance: False
  vectors: False
  state_decoder_unit_mx: False
  raw_waveforms: False # extract raw waveforms for unit matching (session level)
  bombcell: True # Bombcell quality control on Kilosort streams
  unit_match: True # run unit matching across all sessions of an animal

session_IDs:  
  - "017388_SIT_passive_2026-05-06_15-20-34"
  - "017388_SIT_passive_2026-05-10_14-34-20"
  - "017388_SIT_passive_2026-05-10_14-54-12"
  - "017388_SIT_passive_2026-05-10_17-03-18"
  - "017388_SIT_passive_2026-05-10_17-23-46"
  - "017388_SIT_passive_2026-05-11_10-04-32"

  ############# Version 1
  #### Learning Low-freq
  - "017388_SIT_2026-05-11_18-53-42"
  - "017388_SIT_2026-05-12_08-53-25"
  - "017388_SIT_2026-05-12_14-40-51"
  - "017388_SIT_2026-05-12_18-10-20"
  - "017388_SIT_2026-05-13_10-41-58"
  - "017388_SIT_2026-05-13_15-02-24"
  - "017388_SIT_2026-05-13_18-34-02"
  - "017388_SIT_2026-05-14_13-57-02"
  - "017388_SIT_2026-05-14_18-24-13"
  - "017388_SIT_2026-05-15_10-10-21"
  - "017388_SIT_2026-05-15_15-00-12"
  - "017388_SIT_2026-05-15_18-53-17"
  - "017388_SIT_2026-05-16_13-31-40"
  - "017388_SIT_2026-05-16_16-21-44"
  - "017388_SIT_2026-05-16_18-05-17"
  - "017388_SIT_2026-05-17_16-04-59"
  - "017388_SIT_2026-05-17_19-11-26"
  - "017388_SIT_2026-05-18_10-20-44"
  - "017388_SIT_2026-05-18_14-04-33"
  - "017388_SIT_2026-05-18_18-01-54"
  - "017388_SIT_2026-05-19_12-33-40"
  - "017388_SIT_2026-05-21_10-11-23"
  - "017388_SIT_2026-05-22_16-58-49"
  - "017388_SIT_2026-05-25_15-21-35"
  ### High-freq
  - "017388_SIT_2026-05-21_17-49-06"
  - "017388_SIT_2026-05-22_08-38-27"
  - "017388_SIT_2026-05-23_19-19-29"
  - "017388_SIT_2026-05-24_19-22-10"
  ### HighFreq LowFreqdist
  - "017388_SIT_2026-05-25_19-11-59"
  - "017388_SIT_2026-05-26_08-54-55"
  - "017388_SIT_2026-05-26_14-09-10"
  - "017388_SIT_2026-05-26_18-22-01"
  - "017388_SIT_2026-05-27_10-18-59"
  - "017388_SIT_2026-05-27_14-30-23"
  - "017388_SIT_2026-05-28_10-28-50"
  - "017388_SIT_2026-05-29_10-46-53"
  - "017388_SIT_2026-05-30_12-13-07"
  ### LowFreq HighFreqdist
  - "017388_SIT_2026-05-30_15-55-58"
  - "017388_SIT_2026-05-30_19-10-05"
  - "017388_SIT_2026-05-31_09-37-36"
  - "017388_SIT_2026-05-31_12-49-16"
  - "017388_SIT_2026-06-01_17-57-47"
  - "017388_SIT_2026-06-01_20-01-34"
  - "017388_SIT_2026-06-02_10-24-26"
  - "017388_SIT_2026-06-02_14-44-55"
  - "017388_SIT_2026-06-02_18-05-19"
  - "017388_SIT_2026-06-03_10-58-14"
  - "017388_SIT_2026-06-04_13-47-22"
  ### HighFreq LowFreqdist relearning
  - "017388_SIT_2026-06-04_16-29-12"
  - "017388_SIT_2026-06-04_19-14-29"
  - "017388_SIT_2026-06-05_09-15-52"
  - "017388_SIT_2026-06-05_14-26-10"
  - "017388_SIT_2026-06-05_18-32-43"
  - "017388_SIT_2026-06-06_09-48-33"
  - "017388_SIT_2026-06-06_18-23-17"
  - "017388_SIT_2026-06-07_10-07-10"
  - "017388_SIT_2026-06-07_12-43-44"
  - "017388_SIT_2026-06-08_12-47-02"
  # Passive Version 1
  - "017388_SIT_passive_2026-05-11_16-29-57"
  - "017388_SIT_passive_2026-05-20_10-49-40"
  - "017388_SIT_passive_2026-05-23_20-22-35"
  - "017388_SIT_passive_2026-05-25_12-48-33"
  - "017388_SIT_passive_2026-05-29_10-26-39"
  - "017388_SIT_passive_2026-05-30_13-16-12"
  - "017388_SIT_passive_2026-06-03_12-02-49"
  - "017388_SIT_passive_2026-06-04_14-53-09"
  - "017388_SIT_passive_2026-06-08_13-53-08"

  

  # # ############# Version 2
  - "017388_SIT_2026-05-19_15-38-23"
  - "017388_SIT_2026-05-20_11-10-02"
  - "017388_SIT_2026-05-21_14-11-54"
  - "017388_SIT_2026-05-23_15-49-44"
  # #### High-freq
  - "017388_SIT_2026-05-22_13-08-42"
  - "017388_SIT_2026-05-24_11-53-50"
  ##### HighFreq LowFreqdist
  - "017388_SIT_2026-05-28_14-52-09"
  - "017388_SIT_2026-05-29_13-37-58"
  ###### LowFreq HighFreqdist
  - "017388_SIT_2026-06-03_13-46-35"
  ### HighFreq LowFreqdist
  - "017388_SIT_2026-06-06_13-59-58"
  - "017388_SIT_2026-06-08_09-28-22"


  ############# Version 3
  ####### LowFreq
  - "017388_SIT_2026-05-19_18-54-57"
  - "017388_SIT_2026-05-20_19-43-31"
  - "017388_SIT_2026-05-24_15-38-27"
  # HighFreq
  - "017388_SIT_2026-05-23_12-05-01"
  - "017388_SIT_2026-05-25_11-44-43"
  ##### HighFreq LowFreqdist
  - "017388_SIT_2026-05-28_18-29-01"
  - "017388_SIT_2026-05-29_16-01-39"
  ###### LowFreq HighFreqdist
  - "017388_SIT_2026-06-03_18-46-35"
  ##### HighFreq LowFreqdist
  - "017388_SIT_2026-06-07_16-06-16"

  # Passive Version 2
  - "017388_SIT_passive_2026-05-11_16-51-25"
  - "017388_SIT_passive_2026-05-20_19-22-53"
  - "017388_SIT_passive_2026-05-24_12-57-07"
  - "017388_SIT_passive_2026-05-29_14-42-03"
  - "017388_SIT_passive_2026-06-03_14-51-53"
  - "017388_SIT_passive_2026-06-08_10-32-10"
  # Passive Version 3
  - "017388_SIT_passive_2026-05-20_20-44-53"
  - "017388_SIT_passive_2026-05-24_20-27-23"
  - "017388_SIT_passive_2026-05-29_17-03-07"
  - "017388_SIT_passive_2026-06-03_19-49-59"
  - "017388_SIT_passive_2026-06-08_11-15-29"

  



# source of raw data
#src_path: "/home/sobolev/nevermind_ag-grothe/Andrey/data/"
src_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw"

# destination for processed data
#dst_path: "/home/sobolev/nevermind_ag-grothe/Andrey/sandbox/4Kate/processed"
dst_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/processed/"

prj_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/projects/ICproject/"

template_manual_json: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/017388/manual_version1.json"
# template_manual_json: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/017388/manual_version2.json"
# template_manual_json: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/017388/manual_version3.json"

pack:
  drift_coeff: 0.000016666
  adc_sync:
    enabled: True
    f_lo: 2400.0
    f_hi: 6100.0
    scheduler_threads: 8
    io_heavy: 1

kilosort:
  settings_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/017276/kilosort.json"
  #probe_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/data/raw/017276/probe.json"
  save_preprocessed: False
  cuda_device: 3

# single units config: which sorter to use
units:
  source: 'kilosort'
  label_source: 'bombcell' # ks | bombcell

bombcell:
  threads: 32
  resource_slots: 1
  io_heavy: 1
  unit_match_waveforms: True
  force_unit_match_waveform_reextract: False
  stage_raw_dat:
    enabled: True
    root: "/local/scratch/bengala/pplSIT/bombcell_stage"
    cleanup: True
    min_free_gb: 20
  param_overrides:
    maxRPVviolations: 0.4
    minSpatialDecaySlopeExp: 0.005
    tauR_values: [0.0008]
    tauR_valuesMin: 0.0008
    tauR_valuesMax: 0.0008

unit_match:
  conda_env: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/envs/unit_match_py312"
  waveform_source: 'bombcell'
  spike_width: 82
  raw_waveform_threads: 4
  raw_waveform_workers: 4
  raw_waveform_io_heavy: 4
  methods: ["deepunitmatch", "unitmatchpy"]
  deepunitmatch:
    source_path: "/mnt/nevermind.data-share/ag-grothe/AG_Pecka/apps/UnitMatch/UnitMatchPy"
    model_path: null
    tmp_dir:  "/local/scratch/bengala/pplSIT/deepunitmatch_tmp/017388"

io_heavy_lock:
  enabled: False
  path: "/tmp/pplSIT_io_heavy.lock"


# deep lab cut config files
#dlc_config_path: "/home/sobolev/nevermind_ag-grothe/Miguel/DeepLabCut/TrainedModels/implantedSIT-Miguel-2023-06-23/config.yaml"
dlc_config_path: "/mnt/nevermind.data-share/ag-grothe/Miguel/DeepLabCut/TrainedModels/implantedSIT_newSetup-Miguel-2025-01-24/config.yaml"
dlc_shuffle: 1
dlc_trainingsetindex: 1

# moseq config files
moseq_model_path: '/mnt/nevermind.data-share/ag-grothe/Miguel/MoSeq/TrainedModels/hippoSIT2023_noTail_unfiltered/2023_07_13-15_08_10'
cuda_device_to_use: 3

# LFP configuration
lfp:
  n_channels: 384
  source_rate: 30000 # original LFP sampling rate in Hz
  target_rate: 1000  # target LFP sampling rate in Hz
  chunk_size_sec: 10  # chunk size for conversion in seconds
  scheduler_threads: 16
  io_heavy: 1
  aep_dur: 0.25  # Auditory evoked response duration in sec
  aep_pre: 0.12
  aep_sig: 0.125
  artifacts:
    z_thresh: 8.0
    win_ms: 200
    step_ms: 100
    min_dur_ms: 500
    merge_gap_ms: 2000
  aep_ITPC:
    area: 'any'
    metric: 'avg_across_channels'  # weighted_avg, zscored_avg, raw_AEPs (last is 2D)
  baseline:
    min_duration_ms: 500
    stationary_thresh: 0.04  # m/s

# analysis configurations
psth:
  micro:
    latency: 0.25
    bin_count: 151
    shuf_iter_count: 100
    figsize: 4
  macro:
    latency: 7.25
    bin_count: 31
  bootstrap:
    latency: 0.25
    bin_count: 51
    boot_iter_count: 100

# neural manifolds
nMAP_electrodes:
    '009265': [1, 2]
    '009266': [1, 2]
    '57': [1]
    '60': [1, 2]

nMAP_segmentation:
  ft: 'tSNE'
  fp: 70
  speed_thresh: 0.04  # m/s
  margin: 5
  sigma: 0.1
  bin_count: 100
  shuffle_iter_count: 100

# behavioral manifolds
bMAP_segmentation:
  ft: 'tSNE'
  fp: 70
  speed_thresh: 0.04  # m/s
  margin: 5
  sigma: 0.12
  bin_count: 100
  shuffle_iter_count: 100

# metronome
metronome:
  split_ratio: 0.5

# Evoked / sustained manifold
nMAP_EV_SU:
  bin_size: 0.01
  ev_su_lag: 0.12
  k_width: 200  # sampled as activity matrix bins (10ms)
  smooth_su_size: 4  #  rectangular kernel size to smooth sustained part
  smooth_ev_size: 20  #  gaussian kernel size to smooth evoked part

# unit matrix + video merging
video:
  duration: 300  # in seconds
  overlap: 100  # in seconds
  crop_width: 900
  crop_height: 768
  scale_height: 1242
  overwrite: False

# PCA and pairwise correlations for sustained activity
coherence:
  comp_count: 10
  bin_size: 0.01
  win_sizes: [5, 10, 20, 30, 50, 75, 100, 150, 200, 300, 500, 750, 1000, 1500, 2000]  # in number of bins of bin_size
  sustained_start: 0.12

PSTH_micro_bnMAPs:
  units: []  # leave empty for all units

sound_phase_lock:
  n_shuffles: 100
  ipi_for_shuffle: 0.25

sound_phase_lock:
  n_shuffles: 100
  ipi_for_shuffle: 0.25

segments:
  ensembles: False
  tgt_sta_min_pulses: 13
  bgr_sta_min_pulses: 12
  sil_sta_min_pulses: 12
  bgr_run_min_pulses: 2
  sil_run_min_pulses: 4
  dis_sta_min_pulses: 4
  visits:
    min_pulses: 8
    radius: 0.05
  strip_l:
    tgt: 2
    bgr: 1
    sil: 1
    dis: 1
  strip_r:
    tgt: 0
    bgr: 1
    sil: 1
    dis: 1

vectors:
  min_mfr: 0.005
  unit_mx:
    group: 'mx_50ms'
    type: 'mx_sm20_z'
    step: 5
  units_to_exclude:
    '014393_ppcSIT_2025-04-23_20-27-09': ['2-300', '3-350']
